zinserjan/mocha-webpack

package.json
src/cli/index.js
src/cli/parseArgv.js
src/cli/parseConfig.js
test/cli/parseArgv.test.js
test/cli/parseConfig.test.js
test/setup.js

Add a `—opts` argument to the CLI to allow the `mocha-webpack.opts` to live somewhere else.
`--opts` matches the name of the argument that Mocha uses for the same purpose.  Using the same argument name makes it easier to convert an existing project from mocha to mocha-webpack.
With this flag, I was able to simplify the `parseConfig` tests to the point that `babel-plugin-rewire` is no longer needed, so the second commit removes it from the project.

Allow options file to be specified on the command line

---

src/cli/parseArgv.js
test/bin/include.test.js
test/cli/parseArgv.test.js

Cli arguments were parsed in a different way than mocha does it. It was possible to pass multiple arguments to some options without repeating the option. This leads to some unexpected behavior when the test entry was the last option (see #7).
For example the entry of the following command was interpreted as a part of the require option.
```
$ mocha-webpack --require source-map-support/register ./test/entry.js
```
To provide multiple values to some options it's necessary to repeat the option, like the following:
```
$ mocha-webpack  --require source-map-support/register  --require some-other-module ./test/entry.js
```

fix cli arguments with multiple values

---

src/cli/parseArgv.js
test/bin/version.test.js

Fix for `mocha-webpack --version`, see #11

--version option doesn't work, gives error Cannot find module '../package'

---

src/webpack/InjectChangedFilesPlugin.js

The `--watch` option is not working for me – it ends up failing with a syntax error when the code generated by `InjectChangedFilesPlugin` / webpack gets eval'd by `mocha-webpack`. You can verify this error in my sample app:
```sh
git clone git@github.com:thiagoa/sample-app
cd sample-app
npm install
node_modules/.bin/mocha-webpack # Works
node_modules/.bin/mocha-webpack --watch # Does not work
```
I get the following error:
> eval("\"use strict\";\n\n// This gets replaced by webpack with the updated files on rebuild\nvar __webpackManifest__ = ["./6bb2e8176d135c5dda2c2b116019dd85-entry.js","./smoke.spec.js","chai","./lib/chai","assertion-error","./chai/utils","./test","./flag","type-detect","./lib/type","./expectTypes","./getMessage","./getActual","./inspect","./getName","./getProperties",". …

Fix InjectChangedFilesPlugin to escape quotes in webpackManifest files

---

src/cli/parseArgv.js
test/cli/parseArgv.test.js

Mocha uses its defaults when the parameter to `.useColors` is `undefined`: https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L344-L347
Right now, you are always overriding it to `false` unless an argument is given to always override it to `true`, which defeats the point of mocha's default.

Let mocha use its default "colors" setting when not specified

---

package.json
src/webpack/InjectChangedFilesPlugin.js

Updates the `peerDependencies` and updates the `InjectChangedFilesPlugin` for API change in `2.1.0-beta.16`.
All tests pass with `npm install webpack@^1.12.13`, `npm install webpack@2.1.0-beta.15` and `npm install webpack@2.1.0-beta.17`; it also can be successfully used on a large webpack2 codebase with a (tiny...) test suite. Did not test other versions.

Support webpack 2 beta

---

.travis.yml

With  #32 we added support for webpack 2. This PR adjusts the configuration of travis to test webpack@1 and webpack@2.

ci tests for webpack v1 and v2

---

src/webpack/watch.js

This PR addresses #30 and adds support for custom file watcher configuration via watchOptions (see [webpack configuration](https://webpack.github.io/docs/configuration.html#watchoptions-aggregatetimeout))

custom file watcher configuration via watchOptions

---

src/cli/index.js
src/util/glob.js
test/integration/cli/entry.test.js
test/integration/cli/fixture/config/config.resolve-extensions.js
test/unit/util/glob.test.js

Fixes the [failing example](https://github.com/dola/mocha-webpack-fail) in https://github.com/zinserjan/mocha-webpack/issues/48#issuecomment-253546068
This PR allows the usage of defined extensions in `resolve.extensions` as a fallback for module resolution when just a directory is given or nothing. If there is no `resolve.extensions` defined, we just use `.js` files. 
Providing a glob option like `--glob *.js` overrides this behaviour.

use resolve.extensions in webpack config for directory entries

---

README.md
package.json
src/webpack/compiler/createCompiler.js
src/webpack/util/registerSourcemapSupport.js

Including source-map-support by default is necessary before we can switch to an in-memory fs as suggested in #25.

include source-map-support by default

---

README.md
package.json
src/MochaWebpack.js
src/cli/index.js
src/runner/TestRunner.js
src/util/registerRequireHook.js
src/webpack/compiler/createCompiler.js
src/webpack/compiler/createInMemoryCompiler.js
src/webpack/compiler/registerInMemoryCompiler.js
src/webpack/types.js
src/webpack/util/registerRequireHook.js
src/webpack/util/registerSourcemapSupport.js
test/integration/cli/code-splitting.test.js
test/integration/cli/fixture/code-splitting/src/entry/entry1.js
test/integration/cli/fixture/code-splitting/src/entry/entry2.js
test/integration/cli/fixture/code-splitting/src/lazy-load-entry-dynamic.js
test/integration/cli/fixture/code-splitting/src/lazy-load-entry-static.js
test/integration/cli/fixture/code-splitting/test/lazy-load-entry-dynamic.js
test/integration/cli/fixture/code-splitting/test/lazy-load-entry-static.js
test/integration/cli/fixture/code-splitting/webpack.config-test.js

All webpack assets are now handled by an in memory filesystem as suggested in #25. No files are written to disk.
How does it work?
- all compiled files by webpack are stored in [memory-fs](https://github.com/webpack/memory-fs)
- we hook into the path resolution algorithm of all require calls to look also for file existence in the memory-fs
- we hook into the compile algorithm of all require calls to read the bundle from memory
At the moment this works only for `.js` files, cause we need to register each file extension manually. But this should be fine as nodejs only understands `.js`, `.json` and `.node` files and as far as I know webpack emits only `.js` files. 
Tasks:

in-memory filesystem for webpack assets

---

src/runner/configureMocha.js
src/runner/loadReporter.js
test/fixture/customMochaReporter.js
test/integration/cli/fixture/simple/simple.js
test/integration/cli/reporter.test.js
test/unit/runner/loadReporter.test.js

This PR adds support for custom or third-party reporters:
- use custom reporter as function (API only)
- use built-in reporter (like 'spec')
- use custom reporter from node_modules
- use custom reporter relative from cwd
Ref: #58

support custom reporter for mocha

---

package.json
src/cli/index.js
src/createMochaWebpack.js
test/unit/createMochaWebpack.test.js

Export a factory function instead of the main class as nobody should rely on inheritance.

export factory function to use mocha-webpack programmatically

---

src/runner/TestRunner.js
test/integration/cli/watch.test.js

Never ending async tests (done callback gets never called) let mocha hang in watch mode when timeouts are disabled. We need to make sure that all tests gets canceled before we can re-run mocha again.
Example:
```
$ mocha-webpack --timeouts 0 --watch test.js
```
**test.js**
```javascript
var assert = require('assert');
describe('test', function () {
it('runs test', function (done) {
console.log('this will never finish');
});
});
```

mocha hangs in watch mode with disabled timeouts

---

src/webpack/util/getAffectedModuleIds.js
test/integration/cli/code-splitting.test.js
test/integration/cli/fixture/code-splitting/src/cyclic/entry1.js
test/integration/cli/fixture/code-splitting/src/cyclic/entry2.js
test/integration/cli/fixture/code-splitting/src/cyclic/index.js
test/integration/cli/fixture/code-splitting/test/cyclic-load-entry.js

This prevents an error with an cyclic require statement that matches the file itself.

check if module is already marked as affected

---

src/runner/TestRunner.js

Mocha calls the callback in rare cases twice when we abort tests and this means that we register the exception handler also twice.

make sure mocha callback is only called once

---

.travis.yml
package.json
src/webpack/loader/entryLoader.js
test/integration/cli/watch.test.js

This PR fixes several issues in watch mode
- deleting entry files didn't work on windows
- remove caching flag of entry loader (it's not cacheable cause entries could change from outside of loader)
Attempts to make the tests more stable:
- refactored watch tests with promises
- use webpack 1 fork with updated watchpack 1.2.0 until this gets into webpack 1
- retry watch tests until 4 times

Fix --watch issues

---

src/MochaWebpack.js
src/cli/index.js
src/runner/configureMocha.js
test/integration/cli/reporter.test.js
test/unit/MochaWebpack.test.js
test/unit/runner/configureMocha.test.js

Restores mocha' s `--growl` option to show notifications about the test results.

restore --growl

---

docs/guides/code-coverage.md

It seems like the closing `)` of the `concat` is miss-placed here.
In the previous example
```
const somethingTrue = true;
var module = {
loaders: [].concat(
somethingTrue ? {
y: 'y'
} : [],
), // note parens placement
{
z: 'z'
}
}
```
would result in => `Uncaught SyntaxError: Unexpected token '{'`
In this proposed change: 
```
const x = true;
var module = {
loaders: [].concat(
somethingTrue ? {
y: 'y'
} : [],
{
x: 'x'
}
) // note parens placement
}
would result in => Object {loaders: Array(2)}
```
Am I missing something in the previous version?

Fix typo in Istanbul loader example

---

src/cli/requireWebpackConfig.js

Allow mocha-webpack to use a webpack.config.js that exports a function, with 1 arg `env`. This pattern is currently supported in webpack2).
This lets mocha-webpack run something equal to `webpack --env=test`.
example webpack.config.js
```
module.exports = (env = 'dev') => {
const envConfig = require(`./webpack.${env}.js`)
return merge.smart(commonConfig, envConfig)
}
```
which would include webpack.test.js, with your test-specific webpack config.

#140: Support webpack.config.js that exports a function

---

src/util/registerRequireHook.js

This fixes an edge case where a file should be loaded from memory but it does also exist on real fs.

Prefer memory-fs over real fs

---

src/cli/requireWebpackConfig.js
test/unit/cli/fixture/webpackConfig/webpack.config-symlink.js
test/unit/cli/requireWebpackConfig.test.js

`fs.Stats#isFile` doesn't return true for symlinked files. This pull request changes the function that is used to detect whether or not the given configuration exists to call `fs.realpathSync` before calling `fs.lstatSync`.

Fix loading symlinked webpack configuration.

---

src/runner/TestRunner.js
src/util/paths.js
test/integration/cli/entry.test.js

fixes #115, fixes #139
workaround until #145 is ready to merge

Allow absolute paths as entries

---

src/runner/TestRunner.js

Normally the output bundle will be written to and read from memory fs but if the file also exists on the real fs the real fs takes precedence. We need to work around this with an "unique" output path to ensure that the file never exists on file system.
This is also useful when multiple instances of mocha-webpack are running parallel.

use "unique" output path for bundle

---

src/cli/parseArgv.js
test/unit/cli/parseArgv.test.js

use webpack.config.js instead of webpack-config.js to be in sync with documentation and webpack
fixes #185 
fixes #178

fix default value for webpack config

---

src/runner/TestRunner.js
src/webpack/loader/entryLoader.js

fixes #127
Loaders does no longer have access to webpack config. That's why we need to pass all loader options directly to the loader.

fix passing options to loaders

---

docs/installation/cli-usage.md
src/MochaWebpack.js
src/cli/index.js
src/cli/parseArgv.js
src/runner/testRunnerReporter.js
test/integration/cli/quiet.test.js
test/unit/MochaWebpack.test.js

The new messages from #97 can be a little distracting when you're used to just the output from mocha. This just adds a `--quiet` option to stop showing those messages and return to the output behavior pre 1.0.
I'm open to other implementations...would just like the option to opt out of them.

Add an option to quiet the informational messages.

---

package.json
src/cli/parseArgv.js
test/integration/cli/version.test.js
test/unit/cli/parseArgv.test.js

yargs@6 seems to be the latest version that works without too many changes.
All others fails with 
```
Error: Too many arguments provided. Expected max 2 but received 3.
at module.exports (C:\workspace\github\mocha-webpack\node_modules\yargs\lib\argsert.js:31:13)
at Object.Yargs.self.alias (C:\workspace\github\mocha-webpack\node_modules\yargs\yargs.js:244:5)
at parseArgv (C:\workspace\github\mocha-webpack\lib\cli\parseArgv.js:298:60)
at Object.<anonymous> (C:\workspace\github\mocha-webpack\lib\cli\index.js:57:42)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
```
fixes #200

upgrade yargs to support parsing of negative numbers

---

.travis.yml

Add: run ci with node 8 and 9
Fix: due to installing other webpack versions with npm 5 causing errors, I would recommend using yarn instead

test with node 8 and 9 as well use yarn instead of npm

---

.gitattributes

Config from #216 was a bit to strict and affected also binary files like png :see_no_evil:
It's better to use a explicit list for files we want to stay always in lf.

limit lf endings to text files

---

src/runner/testRunnerReporter.js

Works better on Windows (see facebook/create-react-app#2071)

Update the string that clears the console

---

src/util/registerRequireHook.js
src/webpack/compiler/registerInMemoryCompiler.js
src/webpack/types.js
test/unit/util/fixture/fakeModule.js
test/unit/util/registerRequireHook.test.js

Another attempt of #152 based on the proposal in #163.
The idea is to look for modules on memory fs first as the file could also exist on the real fs. This is especially useful when you use mocha-webpack with a plugin that writes the files from memory-fs to disk for debugging purposes or for something else that needs the files.
First step to solve #203 which needs access to the bundled files to start a webworker.

memory fs has priority for require calls

---

docs/installation/webpack-configuration.md
package.json
src/runner/TestRunner.js
test/integration/cli/custom-output-path.test.js
test/integration/cli/fixture/custom-output-path/test/test.js
test/integration/cli/fixture/custom-output-path/webpack.config-test.js
test/integration/cli/fixture/webworker/src/worker.js
test/integration/cli/fixture/webworker/test/worker.js
test/integration/cli/fixture/webworker/webpack.config-test.js
test/integration/cli/webworker.test.js

This PR gives more control on the output settings. All files are still compiled to and read from memory, but this PR allows to use mocha-webpack with a plugin that writes files to disk at the desired location. 
Use case is #203 and maybe #29.
Breaking changes:
- use users `output.filename` if defined, otherwise use webpack's default
- use users `output.path` if defined, otherwise mocha-webpack provides an path (.tmp as before)
- use users `output.publicPath` if `output.path` is defined, otherwise if users `output.path` is missing, mocha-webpack provides an path

 Respect output settings from webpack config

---

.bookignore
package.json

- build docs before npm publish to ensure that this will work
- add bookignore again to deploy a minimum of files
Seems like a published 2.0.0-alpha.0 a few days ago, although the deployment failed. Now all build steps are executed before npm publish.

optimize deployment
